### ISSUE TITLE
土豆

### ISSUE THREAD

**Issue by liukangxu** [iambus/youku-lixian#13]
能否支持土豆网，尤其是土豆网的“原画”画质

**Comment by iambus** [comment]
还是贴几个测试链接吧。

**Comment by liukangxu** [comment]
播放列表：
http://www.tudou.com/albumcover/UMjn60BWOkA.html
http://www.tudou.com/albumcover/u9DkyBKQTmE.html
http://www.tudou.com/albumcover/N4hk0hlUk7s.html
http://www.tudou.com/albumcover/5VKmgzXzbA0.html
单个视频：
http://www.tudou.com/playlist/p/a66346.html
http://www.tudou.com/playlist/p/a65871.html
