### ISSUE TITLE
set executable bit

### ISSUE THREAD

**Issue by lilydjwg** [iambus/youku-lixian#15]
给 video_lixian.py 加上执行权限吧，每次打 python 和脚本路径可不好用。加上执行权限，我可以直接软链接到 $PATH 里。

嗯，还有 #! 别忘了呀。记得写明版本号。Arch 默认的 python 是 python3 的。

**Comment by iambus** [comment]
暂时没有指定版本号，还是用默认的python。因为2也有2.6和2.7之分，指定了2.6，装了2.7的可能就跑不起来了……

**Comment by lilydjwg** [comment]
可以指定 python2 的呀。或者你弄成兼容 python3 的（如果不是已经这样了的话）？

**Comment by iambus** [comment]
怎么指定？

**Comment by lilydjwg** [comment]
`#!/usr/bin/env python2`，如果用户没有 python2 这个程序就只好自己链接了，不过 Arch 有，我记得 Ubuntu 也有。手动安装的的确没有。

**Comment by iambus** [comment]
我用于测试的Ubuntu 10.10没有这个python2。我觉得默认是python 2.x的环境应该比有"python2"的要多些。建议你暂时自己改成python2的。

**Comment by lilydjwg** [comment]
那就增加个 shell 脚本吧，像这样子的：

``` bash
#!/bin/bash

script="$(dirname $0)/video_lixian.py"
if `which python2` &>/dev/null; then
  exec python2 "$script"
else
  exec python "$script"
fi
```

这样应该行了。

我实在不想为了一点小修改再去维护一个新的项目了。。。
