### ISSUE TITLE
能不能自动根据后缀名调用 mp4 或者flv的拼接呢

### ISSUE THREAD

**Issue by daxiawj** [iambus/youku-lixian#2]
能不能自动根据后缀名调用 mp4 或者flv的拼接呢
谢谢

**Comment by iambus** [comment]
自动下载的优酷视频会自动拼接。
如果你说的是手动拼接，目前没有这个打算，因为这需要一个单独的脚本，去判断应该调用flv_join还是mp4_join。虽然这个脚本十分简单，但是我觉得这个脚本的存在毫无必要……其实您可以自己写一个xxx_join，应该是很容易的事情。
另外现在的拼接脚本仅限于优酷的视频，单独使用的可能性（以及成功概率）比较小。
