### ISSUE TITLE
望支持cntv视频下载

### ISSUE THREAD

**Issue by fengleiqi** [iambus/youku-lixian#24]
您好：

```
 诚望youku-lixian 能支持央视网站视频下载。举两个例子，如下。
```

[军旅文化大视野]纪念建军85周年特别节目：《金色的记忆》之《闪闪的红星》(20120527) 
http://news.cntv.cn/20120527/110964.shtml

探索发现 20111120 黄埔军校（一）：到黄埔去
http://xiyou.cntv.cn/v-2e02aa92-40e2-11e1-b140-a4badb469111.html

**Comment by iambus** [comment]
因为视频比较大，没有完全测试。要是合并有问题再发bug吧。
另外这个网站的内容也比较杂。我也只试了你提供的几个链接。同网站的其他网页有可能无法下载。遇到了可以再发bug。

**Comment by fengleiqi** [comment]
动作神速！至为感谢。有bug，再向您汇报。
