### ISSUE TITLE
在专辑下载模式下把能否建立成文件夹形式

### ISSUE THREAD

**Issue by ghost** [iambus/youku-lixian#31]
文件夹名字是播放单的名字，如果下的东西多了，找不着北，顺便把把专辑下载下来的文件名后面的相同文字cut掉

**Comment by iambus** [comment]
请贴一个你要下载的测试链接。

**Comment by ghost** [comment]
http://www.youku.com/playlist_show/id_2435290.html

比如其中一个，Ada The Spy—专辑：《生化危机解说专辑（除四代）》.flv

 把   “—专辑：《生化危机解说专辑（除四代）》”这部分文件名掐掉，作为这个专辑批量下载放置的文件夹的名称

youku --list http://www.youku.com/playlist_show/id_2435290.html 下载完成变成

./
└──生化危机解说专辑（除四代)
    ├── Ada The Spy.flv
    ├── AE前的解闷.flv
    ├── .......
    ├── .......

我只会用awk和sed实现，问题是不如爷的脚本在下载阶段自动完成好

**Comment by iambus** [comment]
比较粗糙的改了下。希望下载的时候创建文件夹，就加个--create-dir或者-c参数。不过我看了下貌似优酷的网页总有些小改动，可能有些网页分析出来的文件名不对。没空细测，遇到文件名不对的再发bug吧。
