### ISSUE TITLE
还望增加一个不合并的选项

### ISSUE THREAD

**Issue by ghost** [iambus/youku-lixian#33]
youku上的我到现在下载的所有视频都不能在android设备上正常播放，mxplayer到每段的结尾处会卡死，vlc直接会退出，无论用何种解码方式，pc上mplayer倒是可以直接看不过终端会冒出很多错误，vlc在硬解下直接Segmentation fault。。既然有点问题，可否添加一个不要合并的选项？毕竟大多数移动设备的播放器会自动添加文件播放列表，连续看不是问题。谢谢了

**Comment by iambus** [comment]
可以。稍后找时间改下。
能不能把你看到的错误（包括使用的视频链接）发一下？我的合并代码差不都属于裸写的，自己连猜带蒙，以前也有人抱怨过说ipad放不了，但是我自己也不太清楚什么问题，有错误信息看一下总是好的。

**Comment by ghost** [comment]
信息放在
https://github.com/iambus/youku-lixian/issues/20
这里了
