### ISSUE TITLE
avfun...

### ISSUE THREAD

**Issue by ahxxm** [iambus/youku-lixian#4]
bilibili都支持了...
然后就是...
“本脚本完全按需编码（目前就我个人的需求）。如果想支持其他在线视频站点的下载，请在github里New Issue：”
这个后面网址和句号之间可以加个空格...

**Comment by iambus** [comment]
只测试了几个视频：如果来源是新浪视频或者优酷视频，应该可以下载。qq来的视频暂时不能下载。如果有你想下的但是下不到，可以发一个新的issue。
