### ISSUE TITLE
土豆

### ISSUE THREAD

**Issue by aristotle9** [iambus/youku-lixian#6]
A站B站上还有一些土豆的视频,望支持,先谢谢了

**Comment by iambus** [comment]
A站和B站引用土豆视频的能够各给一个链接做测试？

**Comment by aristotle9** [comment]
http://www.bilibili.tv/video/av115884/
http://www.acfun.tv/v/ac293372/
这两个应该是土豆的.前者好像只能在Firefox下有效

**Comment by iambus** [comment]
已解决。不过需要注意的是土豆的视频是未分段的。如果下载一个很长的视频中间有网络问题，只能全部重新下载。
