### ISSUE TITLE
能否支持youtube

### ISSUE THREAD

**Issue by liukangxu** [iambus/youku-lixian#9]
路由器使用OpenVPN无缝翻墙，可以正常访问youtube，能否增加对youtube的支持？

**Comment by iambus** [comment]
youtube的话可以试试这个：
http://rg3.github.com/youtube-dl/

我翻墙很不方便，所以短期可能不会支持……

**Comment by liukangxu** [comment]
如有需要，可免费提供私人VPS上搭建的OpenVPN，同时感谢iambus的辛勤付出！
E-mail: liukangxu1996@gmail.com

**Comment by lilydjwg** [comment]
我觉得国外那些让 youtube-dl 支持就好了，没必要造轮子。
